image: python:3.9

stages:
  - test

before_script:
  - pip install -r requirements.txt

test:
  stage: test
  script:
    - pytest --alluredir=allure-results
    - allure generate allure-results -o allure-report --clean
  artifacts:
    paths:
      - allure-report/
    expire_in: 30 days
  after_script:
    - allure serve allure-results